# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.3.8"

gem "expo_turbo-rails", path: "../../rails"
gem "puma", "7.2.1"
gem "rails", "8.1.3"
gem "redis", "5.3.0"
gem "turbo-rails", "2.0.23"

group :development, :test do
  gem "rspec-rails", "7.0.1"
  gem "standard", "1.56.0", require: false
end
