# frozen_string_literal: true

appraise "turbo-rails-2.0.10" do
  gem "rails", "8.1.3"
  gem "turbo-rails", "2.0.10"
end

appraise "turbo-rails-2.0.23" do
  gem "rails", "8.1.3"
  gem "turbo-rails", "2.0.23"
end
